/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aqpg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Mehta
 */
public class GeneratePaper extends javax.swing.JFrame {

    /**
     * Creates new form GeneratePaper
     */
    Connection cn;
    Statement st;
    boolean active=true;
    public GeneratePaper() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=(com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SEProj?zeroDateTimeBehavior=convertToNull","Hasti","hasti");
            st=(com.mysql.jdbc.Statement) cn.createStatement();
        }
        catch(Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb3 = new javax.swing.JComboBox<>();
        cb4 = new javax.swing.JComboBox<>();
        cb7 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb6 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        cb5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the Branch :");

        jLabel2.setText("Enter the Year :");

        jLabel3.setText("Enter the Semester :");

        jLabel4.setText("Enter the Subject :");

        jButton1.setText("Generate Paper");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter the Difficulty Level :");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "I.T.", "EXTC", "EXTR" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First", "Second", "Third", "Fourth" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd" }));
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        cb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths", "Physics", "Chemistry", "Mechanics", "CMS" }));

        cb7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Difficult" }));
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter the Number of Modules :");

        jLabel8.setText("Enter the Number of Questions Per Module :");

        cb6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel9.setText("Enter the Marks Per Module :");

        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        cb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb4, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                            .addComponent(cb3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb7, javax.swing.GroupLayout.Alignment.TRAILING, 0, 150, Short.MAX_VALUE)
                            .addComponent(cb5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String gBranch=(String) cb1.getSelectedItem();
        String gYear=cb2.getSelectedItem().toString();
        String gSem=cb3.getSelectedItem().toString();
        String gSubject=cb4.getSelectedItem().toString();
        String gNModule=cb5.getSelectedItem().toString();
        String gQModule=cb6.getSelectedItem().toString();
        int gMModule=Integer.parseInt(tf.getText());
        String gLevel=cb7.getSelectedItem().toString();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        if(active)
        {
            cb4.removeAllItems();
            setSubject();        
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        if(active)
        {
            String year=cb2.getSelectedItem().toString();
            active=false;
            System.out.println(year);
            cb3.removeAllItems();
            switch(year){
                case "First":
                    cb3.addItem("1st");
                    cb3.addItem("2nd");
                    break;
                case "Second":
                    cb3.addItem("3rd");
                    cb3.addItem("4th");
                    break;
                case "Third":
                    cb3.addItem("5th");
                    cb3.addItem("6th");
                    break;
                case "Fourth":
                    cb3.addItem("7th");
                    cb3.addItem("8th");
                    break;
                default:
                    System.out.println("HIII");
            }
            cb3.setSelectedIndex(0);
            active=true;
//            System.out.println("HI"+cb3.getSelectedItem());
            cb4.removeAllItems();
            setSubject();
            
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        //
        if(active)
        {
            cb4.removeAllItems();
            setSubject();
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb7ActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePaper().setVisible(true);
            }
        });
    }

    public void setSubject(){
        String branch=cb1.getSelectedItem().toString();
        String year=cb2.getSelectedItem().toString();
        String sem=new String();
        if(cb3.getSelectedIndex()!=-1)
            sem=cb3.getSelectedItem().toString();
  
        String subjects[]=new String[10];
        switch(branch)
        {
            case "Computer":
                if(year=="First"){
                    if(sem=="1st"){
                        subjects[0]="Maths 1";
                        subjects[1]="Physics 1";
                        subjects[2]="Chemistry 1";
                        subjects[3]="Mechanics";
//                        subjects[4]="CMS";
                    }
                    else if(sem=="2nd"){
                        subjects[0]="Maths 2";
                        subjects[1]="Physics 2";
                        subjects[2]="Chemistry 2";
                        subjects[3]="Graphics";
//                        subjects[4]="EVS";
                    }
                }
                else if(year=="Second"){
                    if(sem=="3rd"){
                        subjects[0]="Maths ";
                        subjects[1]="Data Structures";
                        subjects[2]="DLDA";
                        subjects[3]="Discrete";
                    }
                    else if(sem=="4th"){
                        subjects[0]="Maths";
                        subjects[1]="AOA";
                        subjects[2]="COA";
                        subjects[3]="Operating System";
                    }  
                }
                else if(year=="Third"){
                    if(sem=="5th"){
                        subjects[0]="Microprocessor";
                        subjects[1]="OS";
                        subjects[2]="SOOAD";
                        subjects[3]="Computer Networks";
                    }
                    else if(sem=="6th"){
                        subjects[0]="SPCC";
                        subjects[1]="Software Engineering";
                        subjects[2]="MCC";
                        subjects[3]="DDBS";
                    }
                }
                else if(year=="Fourth"){
                    if(sem=="7th"){
                        subjects[0]="Digital Signal Processing";
                        subjects[1]="System Security";
                        subjects[2]="AI";
                        subjects[3]="Elective";
                    }
                    else if(sem=="8th"){
                        subjects[0]="Data Warehouse";
                        subjects[1]="Human Machine Interaction";
                        subjects[2]="Distributed Systems";
                        subjects[3]="Elective";
                    }
                }
                break;
            case "I.T.":
                if(year=="First"){
                    if(sem=="1st"){
                        subjects[0]="Maths 1";
                        subjects[1]="Physics 1";
                        subjects[2]="Chemistry 1";
                        subjects[3]="Mechanics";
//                        subjects[4]="CMS";
                    }
                    else if(sem=="2nd"){
                        subjects[0]="Maths 2";
                        subjects[1]="Physics 2";
                        subjects[2]="Chemistry 2";
                        subjects[3]="Graphics";
//                        subjects[4]="EVS";
                    }
                }
                else if(year=="Second"){
                    if(sem=="3rd"){
                        subjects[0]="Maths";
                        subjects[1]="Adv Data Structures";
                        subjects[2]="Discrete";
                        subjects[3]="DLDA";
                    }
                    else if(sem=="4th"){
                        subjects[0]="Maths";
                        subjects[1]="COA";
                        subjects[2]="DBMS";
                        subjects[3]="Operating System";
                    }
                }
                else if(year=="Third"){
                    if(sem=="5th"){
                        subjects[0]="Grpahics and VR";
                        subjects[1]="OS";
                        subjects[2]="Microcontroller and Embedded";
                        subjects[3]="BCE";
                    }
                    else if(sem=="6th"){
                        subjects[0]="SE";
                        subjects[1]="Web Security";
                        subjects[2]="Distributed Systems";
                        subjects[3]="Data Mining";
                    }
                }
                else if(year=="Fourth"){
                    if(sem=="7th"){
                        subjects[0]="Software Project Mgmt";
                        subjects[1]="Cloud Computing";
                        subjects[2]="Intelligent Systems";
                        subjects[3]="Image Processing";
                    }
                    else if(sem=="8th"){
                        subjects[0]="Big Data";
                        subjects[1]="SNMR";
                        subjects[2]="CSM";
                        subjects[3]="ERP";
                    }
                }
                break;
            case "EXTC":
                if(year=="First"){
                    if(sem=="1st"){
                        subjects[0]="Maths 1";
                        subjects[1]="Physics 1";
                        subjects[2]="Chemistry 1";
                        subjects[3]="Mechanics";
//                        subjects[4]="CMS";
                    }
                    else if(sem=="2nd"){
                        subjects[0]="Maths 2";
                        subjects[1]="Physics 2";
                        subjects[2]="Chemistry 2";
                        subjects[3]="Graphics";
//                        subjects[4]="EVS";
                    }
                }
                else if(year=="Second"){
                    if(sem=="3rd"){
                        subjects[0]="Maths";
                        subjects[1]="Circuit Theory";
                        subjects[2]="Digital Circuits";
                        subjects[3]="Signals and Systems";
                    }
                    else if(sem=="4th"){
                        subjects[0]="Maths";
                        subjects[1]="Integrated Circuit";
                        subjects[2]="PCS";
                        subjects[3]="Wave Propogation";
                    }
                }
                else if(year=="Third"){
                    if(sem=="5th"){
                        subjects[0]="Microcontroller and App";
                        subjects[1]="Analog Communication";
                        subjects[2]="Random Signal Analysis";
                        subjects[3]="Integrated Circuits";
                    }
                    else if(sem=="6th"){
                        subjects[0]="Digital Communication";
                        subjects[1]="Discrete Signal";
                        subjects[2]="Communication Networks";
                        subjects[3]="TV Engineering";
                    }
                }
                else if(year=="Fourth"){
                    if(sem=="7th"){
                        subjects[0]="Image and Video Processing";
                        subjects[1]="MCC";
                        subjects[2]="OCN";
                        subjects[3]="MRE";
                    }
                    else if(sem=="8th"){
                        subjects[0]="WCN";
                        subjects[1]="SCN";
                        subjects[2]="IVC";
                        subjects[3]="Speech Processing";
                    }
                }
                break;
            case "ETRX":
                if(year=="First"){
                    if(sem=="1st"){
                        subjects[0]="Maths 1";
                        subjects[1]="Physics 1";
                        subjects[2]="Chemistry 1";
                        subjects[3]="Mechanics";
//                        subjects[4]="CMS";
                    }
                    else if(sem=="2nd"){
                        subjects[0]="Maths 2";
                        subjects[1]="Physics 2";
                        subjects[2]="Chemistry 2";
                        subjects[3]="Graphics";
//                        subjects[4]="EVS";
                    }
                }
                else if(year=="Second"){
                    if(sem=="3rd"){
                        subjects[0]="Maths";
                        subjects[1]="Analog Electronics";
                        subjects[2]="Circuit Theory";
                        subjects[3]="Digital Circuits";
                    }
                    else if(sem=="4th"){
                        subjects[0]="Maths";
                        subjects[1]="Analog Electronics";
                        subjects[2]="PCS";
                        subjects[3]="COA";
                    }
                }
                else if(year=="Third"){
                    if(sem=="5th"){
                        subjects[0]="Microcontroller and App";
                        subjects[1]="Linear Integrated Circuits";
                        subjects[2]="Signals and Systems";
                        subjects[3]="Digital Communication";
                    }
                    else if(sem=="6th"){
                        subjects[0]="VLSI Design";
                        subjects[1]="Computer Organization";
                        subjects[2]="Power Electronics";
                        subjects[3]="DSPP";
                    }
                }
                else if(year=="Fourth"){
                    if(sem=="7th"){
                        subjects[0]="ESD";
                        subjects[1]="ICT";
                        subjects[2]="Power Electronics";
                        subjects[3]="CCN";
                    }
                    else if(sem=="8th"){
                        subjects[0]="VLSI Design";
                        subjects[1]="ANT";
                        subjects[2]="MEMS";
                        subjects[3]="Elective";
                    }
                }
                break;
            default:
//                System.out.println("NOT");
        }
        for(String s:subjects){
            cb4.addItem(s);
        }
        cb4.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private javax.swing.JComboBox<String> cb6;
    private javax.swing.JComboBox<String> cb7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
